[tox]
env_list =
    py310-django32,
    py310-django42,
    py310-django52,
    py312-django52,
    py312-django60,
    py313-django60,
    py314-django60
skip_missing_interpreters = true

[testenv]
package = editable
deps =
    pytest>=8.0
    pytest-django>=4.8
    django32: Django>=3.2,<4.0
    django42: Django>=4.2,<5.0
    django52: Django>=5.2,<6.0
    django60: Django>=6.0,<6.1
commands = pytest -q
